version: '3.1'

services:
  apisnmpprinter-db:
    image: mysql:5.6
    ports:
    - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: sloth_apisnmpprinter_test